In [1]:
import numpy as np 
import math 
import pandas as pd
df = pd.read_csv('kmean_data.csv')
data = df['y']

In [2]:
data = data[:30]
data=np.sort(data)
print(data)

[ 5  7  8 12 14 20 20 25 27 29 32 35 36 40 47 50 51 51 53 53 57 58 59 59
 69 73 74 75 78 79]


In [3]:
b1=np.zeros((10,4)) 
b2=np.zeros((10,4)) 
b3=np.zeros((10,4))

In [45]:
for i in range (0,30,3): 
  k=int(i/3) 
  mean=(data[i] + data[i+1] + data[i+2] )/3
  for j in range(3): 
    b1[k,j]=mean 
print("Mean Bin:\n",b1)

Mean Bin:
 [[ 6.66666667  6.66666667  6.66666667  0.        ]
 [15.33333333 15.33333333 15.33333333  0.        ]
 [24.         24.         24.          0.        ]
 [32.         32.         32.          0.        ]
 [41.         41.         41.          0.        ]
 [50.66666667 50.66666667 50.66666667  0.        ]
 [54.33333333 54.33333333 54.33333333  0.        ]
 [58.66666667 58.66666667 58.66666667  0.        ]
 [72.         72.         72.          0.        ]
 [77.33333333 77.33333333 77.33333333  0.        ]]


In [46]:
for i in range (0,30,3): 
  k=int(i/3) 
  for j in range (3): 
    b2[k,j]=data[i+1] 
print("Median Bin : \n",b2)

Median Bin : 
 [[ 7.  7.  7.  0.]
 [14. 14. 14.  0.]
 [25. 25. 25.  0.]
 [32. 32. 32.  0.]
 [40. 40. 40.  0.]
 [51. 51. 51.  0.]
 [53. 53. 53.  0.]
 [59. 59. 59.  0.]
 [73. 73. 73.  0.]
 [78. 78. 78.  0.]]


In [47]:
for i in range (0,30,3): 
  k=int(i/3) 
  for j in range (3): 
    if (data[i+j]-data[i]) < (data[i+2]-data[i+j]): 
      b3[k,j]=data[i] 
    else: 
      b3[k,j]=data[i+2]   
print("Boundary Bin: \n",b3)

Boundary Bin: 
 [[ 5.  8.  8.  0.]
 [12. 12. 20.  0.]
 [20. 27. 27.  0.]
 [29. 35. 35.  0.]
 [36. 36. 47.  0.]
 [50. 51. 51.  0.]
 [53. 53. 57.  0.]
 [58. 59. 59.  0.]
 [69. 74. 74.  0.]
 [75. 79. 79.  0.]]
